server:
  port: 8091

spring:

  config:
    import:
      - classpath:application-security.yml

  datasource:
    url: jdbc:mysql://localhost:${JDBC_PORT}/${JDBC_DATABASE}?serverTmeZone=Asia/Seoul
    #    url: jdbc:mysql://localhost:3306/matching_bot
    username: scott
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver

  web:
    resources:
      add-mappings: true
    servlet:
      throw-exception-if-no-handler-found: false

  application:
    admin:
      enabled: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  jpa:
    defer-datasource-initialization: true #data.sql이 JPA 초기화 이후에 실행되도록 설정
    hibernate:
      ddl-auto: none # 테이블이 있다면  update 로 변경,
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        highlight_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


  jackson:
    time-zone: Asia/Seoul


#logging:
#  level:
#    org.springframework.web: DEBUG
#    root: DEBUG
#    org.hibernate.SQL: DEBUG


kakao:
  rest-api-key: "KakaoAK 95f4cb7367a36e2e71328edc2c4b9b07"


od:
  cloud:
    key: ${OD_CLOUD_KEY}


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha  # 메서드 정렬
    tags-sorter: alpha        # 태그 정렬
    display-request-duration: true  # 요청 시간 표시
    try-it-out-enabled: true
    syntax-highlight:
      theme: monokai