spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      model: gpt-4o
      options:
        temperature: 0.3

#  profiles:
#    active: local
  cloud:
    aws:
      credentials: # IAM으로 생성한 시크릿키 정보를 입력
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      S3:
        bucket: matchingbot-company-reports    #${S3_BUCKET_NAME} # bucket 이름
        base-url: https://matchingbot-company-reports.s3.us-east-2.amazonaws.com/upload/  #url복사해서붙이기
      region:
        static: us-east-2  # bucket이 위치한 AWS 리전을 설정
      stack:
        auto: false # 자동 스택 생성 기능



jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}

security:
  access:
    permit-all:
      - /api/occupations/**
      - /css/**
      - /js/**
      - /img/**
      - /favicon.ico
      - /.well-known
      - /error/**
      - /auth/**
      - /
      - /main
      - /admin/login
      - /map_popup
      - /api/v1/auth/login
      - /api/v1/auth/refresh
      - /api/v1/attached/report-image-path/**
      - /api/v1/attached/summary-image-path/**
      - /search-page/**
      - /jobs/**
      - /community/**
      - /calendar
      - /job/**
      - /job/detail/**

      - /community/detail/**
      - /api/v1/chatbot/**
      - /api/calendar/**

      - /swagger-ui/**
      - /v3/api-docs
      - /v3/api-docs/**
      - /upload/**
      - /attached/company/**
      - /member/register
      - /company/register
    authenticated-paths:      #authenticated
      - /api/**
    member-paths:
      - /api/maps/**
      - /member/**
      - /community/write
      - /community/edit/**
      - /community/delete/**
      - /community/**
    company-paths:
      - /resumes/**
      - /company/**
      - /job/**
      - /member/view/**
      - /api/occupations/**
      - /community/write
      - /community/edit/**
      - /community/delete/**
    admin-paths:
      - /admin/**
    #      - /company/**
    #      - /job/**